# /qompassai/python/ruff/pyproject.toml
# Qompass AI Ruff Config (pyproject.toml style)
# Copyright (C) 2025 Qompass AI, All rights reserved

[tool.ruff]
exclude = [
  ".bzr", ".direnv", ".eggs", ".git", ".git-rewrite", ".hg",
  ".ipynb_checkpoints", ".mypy_cache", ".nox", ".pants.d",
  ".pyenv", ".pytest_cache", ".pytype", ".ruff_cache", ".svn",
  ".tox", ".venv", ".vscode", "__pypackages__", "_build",
  "buck-out", "build", "dist", "node_modules", "site-packages", "venv"
]
line-length = 88
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B"]
ignore = ["E501", "E401"]
fixable = ["ALL"]
unfixable = ["B"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
exclude = ["*.pyi"]
docstring-code-format = true
docstring-code-line-length = 1

