# ~/.config/uv/uv.toml
# https://docs.astral.sh/uv/reference/settings/
add-bounds = "major"
allow-insecure-host = ["localhost:8080"]
build-constraint-dependencies = []
cache-dir = ".cache/uv"
check-url = "https://pypi.org/simple/"
compile-bytecode = true
concurrent-builds = 10
concurrent-downloads = 10
concurrent-installs = 10
config-settings = { editable_mode = "compat" }
environments = []
exclude-newer = "2006-12-02T02:07:43Z"
extra-index-url = [
  "https://download.pytorch.org/whl/cu128",
  "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html",
  "https://developer.download.nvidia.com/compute/redist"
]
find-links = [
  "https://download.pytorch.org/whl/torch_stable.html",
  "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
]
fork-strategy = "fewest"

[[index]]
url = "https://test.pypi.org/simple"
default = true

index-strategy = "unsafe-best-match"
index-url = "https://pypi.org/simple/"
keyring-provider = "subprocess"
link-mode = "copy"
native-tls = true
no-binary = false
no-binary-package = ["ruff"]
no-build = false
no-build-isolation = true
no-build-isolation-package = []
no-build-package = ["ruff"]
no-cache = false
no-index = false
no-sources = true
prerelease = "allow"
preview = true
publish-url = "https://test.pypi.org/legacy/"
pypy-install-mirror = "https://downloads.python.org/pypy"
python-downloads = "manual"
python-preference = "system"
python-downloads-json-url = "home/phaedrus/.config/uv/python-downloads.json"
python-install-mirror = "https://github.com/astral-sh/python-build-standalone/releases/download"
reinstall = true
reinstall-package = ["ruff"]
required-version = ">=0.5.0"
resolution = "highest"
trusted-publishing = "always"
upgrade = true
upgrade-package = ["ruff"]

[pip]
allow-empty-requirements = true
#all-extras = true
annotation-style = "line"
break-system-packages = true
compile-bytecode = true
config-settings = { editable_mode = "compat" }
#custom-compile-command = "./custom-uv-compile.sh"
emit-build-options = true
emit-index-annotation = true
emit-index-url = true
emit-marker-expression = true
exclude-newer = "2006-12-02T02:07:43Z"
#extra = ["dev", "docs"]
extra-index-url = [
  'https://download.pytorch.org/whl/cu128',
  "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html",
  "https://developer.download.nvidia.com/compute/redist"
]
find-links = [
  'https://download.pytorch.org/whl/torch_stable.html',
  'https://storage.googleapis.com/jax-releases/jax_cuda_releases.html'
]
fork-strategy = "fewest"
index-strategy = "unsafe-best-match"
keyring-provider = 'subprocess'
link-mode = "clone"
no-build-isolation = false
no-sources = false
no-strip-markers = true
prerelease = "allow"
python = "3.13"
python-platform = "x86_64-unknown-linux-gnu"
python-version = "3.13"
reinstall = true
reinstall-package = ["ruff"]
resolution = "highest"
system = true
torch-backend = "auto"
upgrade = true
